version: '3.8'

services:
  panel:
    build: .
    restart: always
    ports:
      - "${PORT:-80}:80"
    environment:
      APP_URL: ${APP_URL:-http://localhost}
      APP_TIMEZONE: ${APP_TIMEZONE:-UTC}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-pterodactyl}
      DB_USERNAME: ${DB_USERNAME:-pterodactyl}
      DB_PASSWORD: ${DB_PASSWORD:-pterodactyl_password}
      REDIS_HOST: ${REDIS_HOST:-127.0.0.1}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-redis}
      MAIL_DRIVER: ${MAIL_DRIVER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-mailhog}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-no-reply@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Pterodactyl}
      # Admin user setup
      ADMIN_USER_SETUP: ${ADMIN_USER_SETUP:-true}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME:-Admin}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME:-User}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Password123}
    volumes:
      - ${VOLUME_DIR:-./volumes}/panel/storage:/var/www/pterodactyl/storage
      - ${VOLUME_DIR:-./volumes}/panel/config:/var/www/pterodactyl/config
      - ${VOLUME_DIR:-./volumes}/panel/certs:/etc/nginx/certs
    depends_on:
      - database
      - redis

  database:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pterodactyl}
      MYSQL_USER: ${MYSQL_USER:-pterodactyl}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pterodactyl_password}
    volumes:
      - ${VOLUME_DIR:-./volumes}/database:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT:-3306}:3306"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ${VOLUME_DIR:-./volumes}/redis:/data

volumes:
  panel_storage:
  panel_config:
  panel_certs:
  database_data: